Vagrant::Config.run do |config|
  config.vm.box = "lucid32"
  config.vm.define(:web) { |c| c.vm.network(:hostonly, "33.33.33.10") }
  config.vm.define(:db)  { |c| c.vm.network(:hostonly, "33.33.33.11") }
end

