require 'rubygems'
load 'deploy'

set :stage_dir, 'environments'
require 'capistrano/ext/multistage'

$:.unshift File.expand_path('../../../lib', __FILE__)
require 'supply_drop/capistrano'

vagrant_gem = `gem which vagrant`.chomp
ssh_options[:keys] =  File.expand_path('../../keys/vagrant', vagrant_gem)
ssh_options[:paranoid] = false
ssh_options[:keys_only] = true
ssh_options[:user_known_hosts_file] = []
ssh_options[:config] = false

set :user, 'vagrant'
