require 'rubygems'
load 'deploy'

$:.unshift File.expand_path('../../../lib', __FILE__)
require 'supply_drop'

vagrant_gem = `gem which vagrant`.chomp
ssh_options[:keys] =  File.expand_path('../../keys/vagrant', vagrant_gem)
ssh_options[:paranoid] = false
ssh_options[:keys_only] = true
ssh_options[:user_known_hosts_file] = []
ssh_options[:config] = false

set :user, 'vagrant'

server '33.33.33.10', :web, :app, :puppet => true
role :db,  '33.33.33.11', :puppet => true
