# this is all to get vagrant working with capistrano
ssh_options[:keys] = File.expand_path('/path/to/ssh/key')
ssh_options[:paranoid] = false
ssh_options[:keys_only] = true
ssh_options[:user_known_hosts_file] = []
ssh_options[:config] = false
set :user, 'ubuntu'

require 'capistrano/supply_drop'

server 'your ec2 server', :web, :app, :db

# Remember to update PATH here substituting /opt/vagrant_ruby/bin
# with the path to your puppet executable
# set :default_env, { 'PATH' => "/opt/vagrant_ruby/bin:$PATH" }
